name: finvu_auth_sdk_flutter
description: "A new auth sdk from finvu AA to complete authentication process without entering the otp."
version: 0.1.1
homepage: https://github.com/Cookiejar-technologies/finvu-auth-sdk-flutter-implementation
repository: https://github.com/Cookiejar-technologies/finvu-auth-sdk-flutter-implementation
issue_tracker: https://github.com/Cookiejar-technologies/finvu-auth-sdk-flutter-implementation/issues

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  pigeon: ^26.0.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.finvu.finvu_auth_sdk
        pluginClass: FinvuAuthSdkPlugin
      ios:
        pluginClass: FinvuAuthSdkPlugin


